services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: helixtrace-clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      - CLICKHOUSE_DB=helixtrace
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=tlZ98k3QR2ycsp
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    restart: unless-stopped
